# Generated by Django 2.2.13 on 2020-07-06 12:25

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20200701_1922'), ('core', '0003_datatable_columns'), ('core', '0004_auto_20200702_1303'), ('core', '0005_datatableaction'), ('core', '0006_auto_20200706_0859')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DatatableAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_row', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('new_row', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('reverted', models.BooleanField(default=False)),
                ('datatable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Datatable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
