# Generated by Django 2.2.13 on 2020-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
