# Generated by Django 2.2.13 on 2020-07-02 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200701_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=None),
        ),
    ]
